[project]
name = "LangDojo"
version = "0.1.0"
description = "LangDojo is a tool for exploring the capabilities of LLMs."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai>=1.61.1",
    "pyright>=1.1.393",
    "rich>=13.9.4",
    "ruff>=0.9.5",
]
